gdata.n64 = {
    A1: [
    "⭐Banjo-Kazooie",
    "⭐Banjo-Tooie",
    "⭐Diddy Kong Racing",
    "⭐GoldenEye 007",
    "⭐Mario Kart 64",
    "⭐Perfect Dark",
    "⭐Super Mario 64",
    "⭐Super Smash Bros.",
    "⭐The Legend of Zelda: Majora's Mask",
    "⭐The Legend of Zelda: Ocarina of Time",
    "Conker's Bad Fur Day",
    "Donkey Kong 64",
    "F-Zero X",
    "Goemon's Great Adventure",
    "Mario Golf",
    "Mario Party 2",
    "Mario Party 3",
    "Mario Party",
    "Mario Tennis",
    "Mystical Ninja Starring Goemon",
    "Paper Mario",
    "Pokémon Stadium 2",
    "Pokémon Stadium",
    "Resident Evil 2",
    "Star Fox 64",
    "Star Wars: Rogue Squadron",
    "Wave Race 64",
    "Wipeout 64",
    ],
    A2: [
    "1080° Snowboarding",
    "Army Men: Air Combat",
    "Bangai-O",
    "Beetle Adventure Racing!",
    "Blast Corps",
    "Bomberman 64: The Second Attack!",
    "Bomberman 64",
    "Bomberman Hero",
    "Bust-A-Move '99",
    "Bust-A-Move 2: Arcade Edition",
    "Dr. Mario 64",
    "Excitebike 64",
    "Gauntlet Legends",
    "International Superstar Soccer '98",
    "Jet Force Gemini",
    "Killer Instinct Gold",
    "Kirby 64: The Crystal Shards",
    "NFL Blitz 2000",
    "Ogre Battle 64: Person of Lordly Caliber",
    "Pilotwings 64",
    "Puyo Puyo SUN 64",
    "Puyo Puyo~n Party",
    "Rayman 2: The Great Escape",
    "Ridge Racer 64",
    "Sin and Punishment",
    "Spider-Man",
    "Star Wars Episode I: Racer",
    "Turok 2: Seeds of Evil",
    "Turok: Dinosaur Hunter",
    "Virtual Pro Wrestling 2: Oudou Keishou",
    "WCW/nWo Revenge",
    "WWF No Mercy",
    "WWF WrestleMania 2000",
    ],
    A3: [
    "007: The World Is Not Enough",
    "Cruis'n Exotica",
    "Cruis'n USA",
    "Cruis'n World",
    "Doom 64",
    "Harvest Moon 64",
    "Hydro Thunder",
    "Magical Tetris Challenge",
    "Mischief Makers",
    "Ms. Pac-Man Maze Madness",
    "NBA Courtside 2: Featuring Kobe Bryant",
    "NHL 99",
    "Nuclear Strike 64",
    "Pokémon Puzzle League",
    "Pokémon Snap",
    "Pokémon Stadium Zero (Japan only)",
    "Quake 64",
    "Quake II",
    "Rush 2: Extreme Racing USA",
    "San Francisco Rush 2049",
    "San Francisco Rush",
    "Shiren the Wanderer 2: Oni Invasion! Shiren Castle!",
    "Snowboard Kids 2",
    "Snowboard Kids",
    "Space Station Silicon Valley",
    "Tetrisphere",
    "Turok 3: Shadow of Oblivion",
    "Wayne Gretzky's 3D Hockey",
    "WinBack",
    "World Driver Championship",
    "Yoshi's Story",
    ],
    B1: [
    "BattleTanx",
    "BattleTanx: Global Assault",
    "Body Harvest",
    "Castlevania",
    "Castlevania: Legacy of Darkness",
    "Chameleon Twist",
    "Chameleon Twist 2",
    "Chopper Attack",
    "Custom Robo",
    "Custom Robo V2",
    "Extreme-G",
    "Extreme-G 2",
    "FIFA '99",
    "Fighter Destiny 2",
    "Fighters Destiny",
    "Forsaken 64",
    "Hybrid Heaven",
    "Ken Griffey, Jr.'s Slugfest",
    "Mickey's Speedway USA",
    "Micro Machines 64 Turbo",
    "NBA Hangtime",
    "NBA Showtime: NBA on NBC",
    "Rocket: Robot on Wheels",
    "S.C.A.R.S.",
    "Shadow Man",
    "Star Wars: Episode I: Battle for Naboo",
    "Stunt Racer 64",
    "The New Tetris",
    "Tony Hawk's Pro Skater",
    "Tony Hawk's Pro Skater 2",
    "Top Gear Hyper Bike",
    "Top Gear Overdrive",
    "Top Gear Rally",
    "Toy Story 2: Buzz Lightyear to the Rescue",
    "Turok: Rage Wars",
    "V-Rally Edition '99",
    "Wetrix",
    "Worms Armageddon",
    ],
    B2: [
    "All-Star Baseball 2001",
    "Army Men: Sarge's Heroes",
    "Bomberman 64: Arcade Edition",
    "Choro Q 64 2",
    "Doubutsu no Mori",
    "Duke Nukem 64",
    "Duke Nukem: Zero Hour",
    "Glover",
    "Indiana Jones and the Infernal Machine",
    "Knockout Kings 2000",
    "Mortal Kombat 4",
    "Off Road Challenge",
    "Penny Racers",
    "Ready 2 Rumble Boxing",
    "Ready 2 Rumble Boxing: Round 2",
    "Road Rash 64",
    "Star Soldier: Vanishing Earth",
    "Susume! Taisen Puzzle-Dama",
    "Tony Hawk's Pro Skater 3",
    "Top Gear Rally 2",
    "Vigilante 8",
    "Vigilante 8: 2nd Offense",
    ],
    B3: [
    "Command & Conquer",
    "Duck Dodgers Starring Daffy Duck",
    "F-1 World Grand Prix",
    "F-1 World Grand Prix II",
    "F1 Pole Position 64",
    "F1 Racing Championship",
    "Flying Dragon",
    "Hot Wheels Turbo Racing",
    "Iggy's Reckin' Balls",
    "Indy Racing 2000",
    "LEGO Racers",
    "Mace: The Dark Age",
    "Monaco Grand Prix",
    "Monster Truck Madness 64",
    "StarCraft 64",
    ],
    C1: [
    "Big Mountain 2000 / Snow Speeder",
    "Buck Bumble",
    "California Speed",
    "Hexen",
    "Mega Man 64",
    "Polaris SnoCross",
    "Rally Challenge 2000",
    "Roadsters Trophy",
    "Shadowgate 64: Trials of the Four Towers",
    "South Park Rally",
    "Star Wars: Shadows of the Empire",
    "Wonder Project J2: Corlo no Mori no Josette",
    ],
    C2: [
    "Army Men: Sarge's Heroes 2",
    "Destruction Derby 64",
    "Gex 3: Deep Cover Gecko",
    "Gex 64: Enter the Gecko",
    "Jeremy McGrath Supercross 2000",
    "Lode Runner 3-D",
    "Mortal Kombat Trilogy",
    "Rampage 2: Universal Tour",
    "Rampage World Tour",
    "Rat Attack!",
    "Robotron 64",
    "SD Hiryu no Ken Densetsu",
    "Super Robot Wars 64",
    "Tom Clancy's Rainbow Six",
    ],
    C3: [
    "A Bug's Life",
    "Aero Fighters Assault",
    "AeroGauge",
    "Armorines: Project S.W.A.R.M.",
    "Automobili Lamborghini",
    "Centre Court Tennis",
    "Charlie Blast's Territory",
    "Dezaemon 3D",
    "Disney's Tarzan",
    "Last Legion UX",
    "MRC: Multi-Racing Championship",
    "Nightmare Creatures",
    "South Park",
    "Utchan Nanchan no Hono no Challenger",
    "Virtual Pool 64",
    ],
    D: [ // Dubious or Skeptical
    "Aidyn Chronicles: The First Mage",
    "Bass Rush: ECOGEAR PowerWorm Championship",
    "Battlezone: Rise of the Black Dogs",
    "CyberTiger",
    "Dance Dance Revolution: Disney Dancing Museum",
    "Donald Duck: Goin' Quackers",
    "Doraemon 2: Nobita to Hikari no Shinden",
    "Doraemon 3: Nobita no Machi SOS!",
    "Doraemon: Nobita to Mittsu no Seireiseki",
    "International Track & Field 2000",
    "Itoi Shigesato no Bass Tsuri No. 1 Ketteihan!",
    "Mission: Impossible",
    "Monopoly",
    "NASCAR 2000",
    "NASCAR 99",
    "Nagano Winter Olympics '98",
    "Namco Museum 64",
    "Nushi Tsuri 64: Shiokaze ni Notte",
    "Nushi Tsuri 64",
    "PGA European Tour",
    "Quest 64",
    "Rakugakids",
    "SimCity 2000",
    "Tetris 64",
    "Tigger's Honey Hunt",
    "Tom and Jerry in Fists of Furry",
    "Tonic Trouble",
    "Virtual Chess 64",
    "Virtual Pro Wrestling 64",
    "WCW vs. nWo: World Tour",
    ],
    E: [ // Bad
    "AI Shogi 3",
    "All Star Tennis '99",
    "Bass Hunter 64",
    "Bass Masters 2000",
    "Deadly Arts",
    "Densha de GO! 64",
    "Earthworm Jim 3D",
    "GT 64: Championship Edition",
    "Goemon: Mononoke Sugoroku",
    "Hey You, Pikachu!",
    "Knife Edge: Nose Gunner",
    "Mario no Photopi",
    "Midway's Greatest Arcade Hits: Volume 1",
    "Morita Shogi 64",
    "Onegai Monsters",
    "Re-Volt",
    "Robopon 64: Robot Ponkottsu 64",
    "Saikyou Habu Shogi",
    "Shin Nippon Pro Wrestling: Toukon Road - Brave Spirits",
    "Shin Nippon Pro Wrestling: Toukon Road 2 - The Next Generation",
    "Tamagotchi 64: Minna de Tamagotchi World",
    "Taz Express",
    "Xena: Warrior Princess: The Talisman of Fate",
    "Yakouchuu 2: Satsujin Kouro",
    ],
    F: [ // Terrible
    "64 Hanafuda: Tenshi no Yakusoku",
    "64 Oozumou 2",
    "64 Oozumou",
    "64 Trump Collection: Alice no Waku Waku Trump World",
    "Airboarder 64",
    "Asteroids Hyper 64",
    "Bakushou Jinsei 64: Mezase! Resort Ou",
    "Batman Beyond: Return of the Joker",
    "Bio F.R.E.A.K.S.",
    "Blues Brothers 2000",
    "Brunswick Circuit Pro Bowling",
    "Carmageddon 64",
    "ClayFighter 63⅓",
    "ClayFighter Sculptor's Cut",
    "Daikatana",
    "Dark Rift",
    "Derby Stallion 64",
    "Dual Heroes",
    "ECW Hardcore Revolution",
    "Eikou no St Andrews",
    "Elmo's Letter Adventure",
    "Elmo's Number Journey",
    "Fighting Force 64",
    "Fox Sports College Hoops '99",
    "Getter Love!!: Chou Renai Party Game Tanjou",
    "Golden Nugget 64",
    "Hamster Monogatari 64",
    "Heiwa Pachinko World 64",
    "Hercules: The Legendary Journeys",
    "Ide Yosuke no Mahjong Juku",
    "Jangou Simulation Mahjong Michi 64",
    "Jeopardy!",
    "Jikkyou GI Stable",
    "Jinsei Game 64",
    "Kira tto Kaiketsu! 64 Tanteidan",
    "Mahjong 64",
    "Mahjong Hourouki Classic",
    "Mahjong Master",
    "Masters '98: Harukanaru Augusta",
    "Mike Piazza's Strike Zone",
    "Milo's Astro Lanes",
    "Mortal Kombat Mythologies: Sub-Zero",
    "Neon Genesis Evangelion",
    "Nintama Rantarou 64 Game Gallery",
    "PD Ultraman Battle Collection 64",
    "Pachinko 365 Nichi",
    "Paperboy 64",
    "Parlor! Pro 64: Pachinko Jikki Simulation",
    "Power Rangers Lightspeed Rescue",
    "Premier Manager 64",
    "Pro Mahjong Kiwame 64",
    "Pro Mahjong Tsuwamono 64",
    "Razor Freestyle Scooter",
    "Rugrats in Paris: The Movie",
    "Rugrats: Scavenger Hunt",
    "Scooby-Doo! Classic Creep Capers",
    "South Park: Chef's Luv Shack",
    "Space Invaders",
    "Starshot: Space Circus Fever",
    "Super B-Daman: Battle Phoenix 64",
    "Super Bowling",
    "Super Robot Spirits",
    "Supercross 2000",
    "Superman",
    "The Powerpuff Girls: Chemical X-traction",
    "Transformers: Beast Wars Transmetals",
    "Twisted Edge Extreme Snowboarding",
    "WCW Backstage Assault",
    "WCW Mayhem",
    "WCW Nitro",
    "WWF Attitude",
    "WWF War Zone",
    "Waialae Country Club: True Golf Classics",
    "War Gods",
    "Wheel of Fortune",
    "Zool: Majuu Tsukai Densetsu",
    ],
    X: [ // Skip (typically sports games that are too similar to other games)
    // Notable or Misc
    "Wayne Gretzky's 3D Hockey '98",    
    "International Superstar Soccer 2000",
    "Kobe Bryant in NBA Courtside",
    "Major League Baseball Featuring Ken Griffey, Jr.",
    // Hockey
    "NHL Blades of Steel '99",
    "NHL Breakaway '98",
    "NHL Breakaway '99",
    "Olympic Hockey Nagano '98",
    // Basketball
    "NBA In The Zone '98",
    "NBA In The Zone '99",
    "NBA In The Zone 2000",
    "NBA Jam '99",
    "NBA Jam 2000",
    "NBA Live 2000",
    "NBA Live 99",
    // Soccer
    "FIFA Soccer 64",
    "FIFA: Road to World Cup 98",
    "International Superstar Soccer 64",
    "J.League Dynamite Soccer 64",
    "J.League Eleven Beat 1997",
    "J.League Live 64",
    "J.League Tactics Soccer",
    "Jikkyou World Soccer 3",
    "Michael Owen's WLS 2000",
    "World Cup 98",
    // Baseball
    "All-Star Baseball 2000",
    "All-Star Baseball 99",
    "Bottom of the 9th",
    "Chou-Kuukan Night Pro Yakyuu King 2",
    "Chou-Kuukan Night Pro Yakyuu King",
    "Famista 64",
    "Jikkyou Powerful Pro Yakyuu 2000",
    "Jikkyou Powerful Pro Yakyuu 4",
    "Jikkyou Powerful Pro Yakyuu 5",
    "Jikkyou Powerful Pro Yakyuu 6",
    "Jikkyou Powerful Pro Yakyuu Basic-ban 2001",
    "Power League 64",
    "Triple Play 2000",
    // USA Football
    "Madden Football 64",
    "Madden NFL 2000",
    "Madden NFL 2001",
    "Madden NFL 2002",
    "Madden NFL 99",
    "NFL Blitz 2001",
    "NFL Blitz Special Edition",
    "NFL Blitz",
    "NFL Quarterback Club '98",
    "NFL Quarterback Club '99",
    "NFL Quarterback Club 2000",
    "NFL Quarterback Club 2001",
    ],
};
