gdata.sms = {
    A1: [ // Good
    ],
    A2: [
    ],
    A3: [
    "Alex Kidd in Miracle World",
    "Alex Kidd in Shinobi World",
    "Asterix",
    "Castle of Illusion Starring Mickey Mouse",
    "Fantasy Zone",
    "Fantasy Zone II: The Tears of Opa-Opa",
    "Final Bubble Bobble",
    "✋GG Aleste II",
    "✋GG Aleste III",
    "Golden Axe Warrior",
    "Golvellius: Valley of Doom",
    "James Pond 2: Codename RoboCod",
    "Land of Illusion Starring Mickey Mouse",
    "✋Legend of Illusion Starring Mickey Mouse",
    "✋Lucky Dime Caper Starring Donald Duck",
    "Master of Darkness",
    "Ninja Gaiden",
    "Operation Wolf",
    "Phantasy Star🌐",
    "Power Strike",
    "Psycho Fox",
    "R-Type",
    "✋Ristar",
    "✋Royal Stone: Hirakareshi Toki no Tobira🌐",
    "Shinobi",
    "Sonic the Hedgehog",
    "Sonic the Hedgehog 2",
    "✋Sonic the Hedgehog Triple Trouble",
    "✋Super Star Wars: Return of the Jedi",
    "✋Sylvan Tale🌐",
    "✋The GG Shinobi",
    "✋The GG Shinobi II: The Silent Fury",
    "Wonder Boy III: The Dragon's Trap",
    "Wonder Boy in Monster Land",
    "Wonder Boy in Monster World",
    "Ys: The Vanished Omens",
    "Zillion",
    ],
    B1: [ // Decent
    ],
    B2: [
    ],
    B3: [
    "Alien 3",
    "✋Arena: Maze of Death",
    "Asterix and the Great Rescue",
    "Asterix and the Secret Mission",
    "Astro Warrior",
    "Ayrton Senna's Super Monaco GP II",
    "✋Baku Baku Animal",
    "Bank Panic",
    "✋Batman Returns",
    "Battle Out Run",
    "✋Berlin no Kabe",
    "Buggy Run",
    "California Games",
    "✋Chakan: The Forever Man",
    "Choplifter",
    "Chuck Rock",
    "Chuck Rock II: Son of Chuck",
    "✋Columns",
    "✋Crystal Warriors",
    "Daffy Duck in Hollywood",
    "✋Deep Duck Trouble Starring Donald Duck",
    "✋Defenders of Oasis",
    "Desert Strike: Return to the Gulf",
    "✋Devilish",
    "✋Donald no Magical World",
    "✋Dr. Robotnik's Mean Bean Machine",
    "✋Ecco the Dolphin",
    "✋Ecco: The Tides of Time",
    "Gain Ground",
    "Gauntlet",
    "✋GG Aleste",
    "✋Godzilla: Kaijuu no Daishingeki🌐",
    "Golden Axe",
    "Golfamania",
    "✋GP Rider",
    "✋Gunstar Heroes",
    "✋Halley Wars",
    "Hang-On",
    "Impossible Mission",
    "✋Jungle Strike",
    "Kenseiden",
    "✋Kishin Douji Zenki🌐",
    "Lemmings",
    "✋Lunar: Samposuru Gakuen🌐",
    "✋Magical Puzzle Popils",
    "✋Megami Tensei Gaiden: Last Bible🌐",
    "✋Megami Tensei Gaiden: Last Bible S🌐",
    "Micro Machines",
    "✋Micro Machines 2: Turbo Tournament",
    "✋Mighty Morphin Power Rangers",
    "✋Mighty Morphin Power Rangers: The Movie",
    "Montezuma's Revenge",
    "Ms. Pac-Man",
    "✋Ms. Pac-Man",
    "✋Pac-Man",
    "Pac-Mania",
    "Penguin Land",
    "Populous",
    "Power Strike II",
    "Prince of Persia",
    "✋Psychic World",
    "✋Puyo Puyo",
    "✋Puyo Puyo 2",
    "Rainbow Islands",
    "Rastan",
    "Road Rash",
    "✋S.S. Lucifer: Man Overboard!",
    "Secret Command",
    "Sensible Soccer",
    "Shanghai",
    "✋Shining Force - The Sword of Hajya",
    "✋Shining Force Gaiden", // no translation yet
    "✋Shining Force Gaiden: Final Conflict🌐",
    "✋Skweek (aka Slider)",
    "Slap Shot",
    "Solomon no Kagi – Oujo Rihita no Namida",
    "✋Sonic Chaos",
    "✋Sonic Drift",
    "✋Sonic Drift 2",
    "✋Star Wars",
    "Streets of Rage",
    "✋Streets of Rage 2",
    "✋Super Off Road",
    "Super Space Invaders",
    "✋Tails Adventure",
    "The New Zealand Story",
    "✋Tintin au Tibet",
    "✋Wizard Pinball",
    "Wonder Boy",
    "Zool",
    ],
    C1: [ // Acceptable
    ],
    C2: [
    ],
    C3: [
    "Aerial Assault",
    "Air Rescue",
    "Alex Kidd: The Lost Stars",
    "Alien Storm",
    "Alien Syndrome",
    "✋Alien Syndrome",
    "Argos no Juujiken",
    "Aztec Adventure",
    "✋Batter Up",
    "✋Battletoads",
    "Bomber Raid",
    "✋Bust-A-Move",
    "Captain Silver",
    "Cheese Cat-Astrophe Starring Speedy Gonzales",
    "✋Choplifter III",
    "✋CJ Elephant Fugitive",
    "✋Coca-Cola Kid",
    "Cool Spot",
    "Danan: The Jungle Fighter",
    "✋Desert Strike: Return to the Gulf",
    "✋Disney's Aladdin",
    "Disney's The Jungle Book",
    "Disney's The Lion King",
    "✋Doraemon: Nora no Suke no Yabou",
    "Dragon Crystal",
    "✋Dropzone",
    "Dynamite Dux",
    "Enduro Racer",
    "✋Eternal Legend🌐",
    "F1",
    "✋F1 World Championship Edition",
    "✋Factory Panic",
    "Fantastic Dizzy",
    "✋Fantasy Zone Gear",
    "Fantasy Zone: The Maze",
    "✋Fatal Fury Special",
    "✋FIFA International Soccer",
    "Forgotten Worlds",
    "✋Frank Thomas' Big Hurt Baseball",
    "✋Fray: Shuugyouhen",
    "✋Galaga '91",
    "Galaxy Force",
    "✋Gear Works",
    "Ghost House",
    "Ghouls 'n Ghosts",
    "Global Defense",
    "Global Gladiators",
    "✋Griffin",
    "✋Head Buster",
    "✋Home Alone",
    "✋Hook",
    "✋J.League GG Pro Striker '94",
    "✋J.League Soccer: Dream Eleven",
    "✋James Pond 3: Operation Starfish",
    "Joe Montana Football",
    "✋Journey from Darkness: Strider Returns",
    "✋Judge Dredd",
    "✋Jurassic Park",
    "✋Kawasaki Superbike Challenge",
    "Klax",
    "✋Klax",
    "✋Krusty's Fun House",
    "Kung Fu Kid",
    "Line of Fire",
    "✋Madou Monogatari A: Dokidoki Vacation🌐",
    "✋Madou Monogatari I: Mittsu no Madouryoku🌐",
    "✋Madou Monogatari II: Arles 16-Sai🌐",
    "✋Madou Monogatari III: Kyuukyoku Joou-Sama🌐",
    "✋Magic Knight Rayearth",
    "✋Magical Tarurūto-kun",
    "✋Mappy",
    "Masters of Combat",
    "✋Mega Man",
    "Michael Jackson's Moonwalker",
    "Miracle Warriors: Seal of the Dark Lord",
    "✋Moldorian: Hikari to Yami no Kyoudai🌐",
    "✋Nazo Puyo",
    "✋Nazo Puyo 2",
    "✋Nazo Puyo: Arle no Roux",
    "✋NBA Jam",
    "✋NBA Jam Tournament Edition",
    "✋NHL Hockey",
    "✋Ninja Gaiden",
    "✋Ninku Gaiden: Heroyuki Daikatsugeki",
    "Olympic Gold: Barcelona '92",
    "Out Run",
    "Out Run Europa",
    "✋Pac-Attack",
    "Paperboy",
    "✋Pengo",
    "✋Pete Sampras Tennis",
    "✋Phantasy Star Gaiden",
    "✋Phantom 2040",
    "Pit Pot",
    "✋Pop Breaker",
    "✋Power Drive",
    "✋Primal Rage",
    "Psychic World",
    "✋Puzzle & Action: Ichidant-R GG",
    "✋Puzzle & Action: Tanto-R",
    "Quartet",
    "✋Quest for the Shaven Yak Starring Ren Hoëk & Stimpy",
    "✋R.B.I. Baseball '94",
    "R.C. Grand Prix",
    "Rampage",
    "Rampart",
    "Reggie Jackson Baseball",
    "RoboCop Versus The Terminator",
    "Sagaia",
    "✋Samurai Shodown",
    "✋Sonic Labyrinth",
    "✋Sonic the Hedgehog Spinball",
    "✋Soukoban",
    "Speedball",
    "Speedball 2",
    "SpellCaster",
    "Star Wars",
    "✋Striker",
    "Submarine Attack",
    "✋Super Columns",
    "✋Super Golf",
    "Super Kick-Off",
    "✋Tails' Skypatrol",
    "✋Taisen-gata: Daisenryaku G", // no translation yet
    "Taz-Mania",
    "Teddy Boy",
    "✋Tempo Jr.",
    "✋Tengen World Cup Soccer (Kick & Rush)",
    "Tennis Ace",
    "✋Tesserae",
    "✋The Berenstain Bears' Camping Adventure",
    "✋The Chessmaster",
    "✋The Excellent Dizzy Collection",
    "The Flash",
    "✋The Lost World: Jurassic Park",
    "✋The Majors: Pro Baseball",
    "The Ninja",
    "✋The Smurfs",
    "✋The Smurfs 2: Travel the World",
    "The Terminator",
    "Time Soldiers",
    "Ultima IV: Quest of the Avatar",
    "✋Urban Strike",
    "Vigilante",
    "✋Wagyan Land",
    "Walter Payton Football",
    "Wimbledon",
    "Wimbledon 2",
    "World Class Leader Board",
    "World Grand Prix",
    "✋World Series Baseball",
    "✋World Series Baseball '95",
    "✋X-Men",
    "Zillion II: The Tri Formation",
    "✋Zoop",
    ],
    D: [ // Dubious or Skeptical
    ],
    E: [ // Bad
    "20 em 1",
    "✋5 in 1 Funpak",
    "✋Aah! Harimanada",
    "Ace of Aces",
    "Action Fighter",
    "✋Aerial Assault",
    "After Burner",
    "Alex Kidd BMX Trial",
    "Alex Kidd: High-Tech World",
    "ALF",
    "Altered Beast",
    "✋Andre Agassi Tennis",
    "Andre Agassi Tennis",
    "✋Arcade Classics",
    "Arcade Smash Hits",
    "✋Arch Rivals",
    "✋Ariel the Little Mermaid",
    "Assault City",
    "✋Ax Battler: A Legend of Golden Axe",
    "Back to the Future II",
    "Back to the Future III",
    "Basketball Nightmare",
    "✋Batman Forever",
    "✋Battleship: The Classic Naval Combat Game",
    "Battletoads in Battlemaniacs",
    "✋Beavis and Butt-Head",
    "✋Bishoujo Senshi Sailor Moon S",
    "Black Belt",
    "Blade Eagle 3-D",
    "Bonanza Bros.",
    "✋Bram Stoker's Dracula",
    "Bram Stoker's Dracula",
    "✋Bugs Bunny in Double Trouble",
    "✋Buster Ball",
    "✋Buster Fight",
    "✋Caesars Palace",
    "California Games 2",
    "✋Captain America and The Avengers",
    "✋Casino FunPak",
    "Casino Games",
    "Castelo Rá-Tim-Bum",
    "Champions of Europe",
    "✋Championship Hockey",
    "Championship Hockey",
    "✋Chicago Syndicate",
    "✋Cliffhanger",
    "Cloud Master",
    "✋Clutch Hitter",
    "Comical Machine Gun Joe",
    "✋Cosmic Spacehead",
    "Cosmic Spacehead",
    "✋Crayon Shin-chan: Taiketsu! Kantam Panic!!",
    "✋Cutthroat Island",
    "Cyborg Hunter",
    "Dead Angle",
    "Desert Speedtrap Starring Road Runner & Wile E. Coyote",
    "Dick Tracy",
    "Disney's Ariel the Little Mermaid",
    "✋Disney's Bonkers: Wax Up!",
    "Disney's Bonkers: Wax Up!",
    "✋Doraemon: Wakuwaku Pocket Paradise",
    "✋Double Dragon",
    "Double Dragon",
    "Double Hawk",
    "✋Dragon: The Bruce Lee Story",
    "Dragon: The Bruce Lee Story",
    "✋Dunk Kids",
    "Dynamite Duke",
    "✋Dynamite Headdy",
    "Dynamite Headdy (Brazil)",
    "E-SWAT",
    "✋Earthworm Jim",
    "Earthworm Jim",
    "✋Ernie Els Golf",
    "✋Evander Holyfield's Real Deal Boxing",
    "✋F-15 Strike Eagle",
    "F-16 Fighting Falcon",
    "✋Faceball 2000",
    "Férias Frustradas do Pica-Pau",
    "✋FIFA Soccer 96",
    "Fire & Forget II",
    "Fire and Ice",
    "✋Foreman For Real",
    "✋Fred Couples Golf",
    "✋From TV Animation: Slam Dunk: Shouri he no Starting 5",
    "✋G-LOC: Air Battle",
    "G-LOC: Air Battle",
    "Galactic Protector",
    "✋Gamble Panic",
    "✋Gambler Jikochuushin Ha",
    "Gangster Town",
    "✋Garfield: Caught in the Act",
    "✋GG Portrait: Pai Chan",
    "✋GG Portrait: Yuuki Akira",
    "Ghostbusters",
    "GP Rider",
    "Great Baseball",
    "Great Baseball (1985)",
    "Great Basketball",
    "Great Football",
    "Great Golf",
    "Great Golf (1986)",
    "Great Ice Hockey",
    "Great Soccer (1985)",
    "Great Volleyball",
    "✋Greendog: The Beached Surfer Dude!",
    "Heavyweight Champ",
    "✋Heavyweight Champ (George Foreman's KO Boxing)",
    "Heroes of the Lance",
    "High School! Kimengumi",
    "Home Alone",
    "✋Honō no Dōkyūji: Dodge Danpei",
    "Hoshi wo Sagashite...",
    "✋House of Tarot",
    "✋Hurricanes",
    "✋Hyokkori Hyoutan Jima: Hyoutan Jima no Daikoukai",
    "✋Hyper Pro Yakyuu '92",
    "✋Indiana Jones and the Last Crusade",
    "Indiana Jones and the Last Crusade: The Action Game",
    "✋Iron Man/X-O Manowar in Heavy Metal",
    "✋James Bond 007: The Duel",
    "James Bond 007: The Duel",
    "✋Jeopardy!",
    "✋Jeopardy! Sports Edition",
    "✋Junction",
    "✋Kaitou Saint Tail",
    "✋Kenyuu Densetsu Yaiba",
    "✋Kinetic Connection",
    "King's Quest: Quest for the Crown",
    "✋Kuni-Chan no Game Tengoku",
    "✋Kuni-Chan no Game Tengoku Part 2",
    "Laser Ghost",
    "✋Last Action Hero",
    "Lord of the Sword",
    "✋Madden 96",
    "✋Madden NFL '95",
    "✋Magic Knight Rayearth 2: Making of Magic Knight",
    "Mahjong Sengoku Jidai",
    "✋Marble Madness",
    "Marble Madness",
    "✋Marko's Magic Football",
    "Marksman Shooting & Trap Shooting",
    "Maze Hunter 3-D",
    "Megumi Rescue",
    "Mercs",
    "✋Mickey's Ultimate Challenge",
    "Mickey's Ultimate Challenge",
    "Missile Defense 3-D",
    "✋MLBPA Baseball",
    "Monopoly",
    "✋Monster Truck Wars",
    "✋Mortal Kombat",
    "Mortal Kombat",
    "✋Mortal Kombat 3",
    "Mortal Kombat 3",
    "✋Mortal Kombat II",
    "Mortal Kombat II",
    "My Hero",
    "✋NBA Action Starring David Robinson",
    "Nekyuu Kousien",
    "✋NFL '95",
    "✋NFL Quarterback Club",
    "✋NFL Quarterback Club 96",
    "✋NHL All-Star Hockey",
    "✋Ninku",
    "✋Ninku 2: Tenkuryu-e no Michi",
    "✋Out Run",
    "Out Run 3-D",
    "✋Panzer Dragoon Mini",
    "✋Paperboy 2",
    "Parlour Games",
    "✋Pet Club: Inu Daisuki!",
    "✋Pet Club: Neko Daisuki!",
    "✋PGA Tour 96",
    "✋PGA Tour Golf",
    "PGA Tour Golf",
    "✋PGA Tour Golf II",
    "✋Phantasy Star Adventure",
    "✋Pinball Dreams",
    "Pit-Fighter",
    "✋Pocket Jansou",
    "✋Poker Face Paul's Blackjack",
    "✋Poker Face Paul's Gin",
    "✋Poker Face Paul's Poker",
    "✋Poker Face Paul's Solitaire",
    "✋Popeye: Beach Volleyball",
    "Poseidon Wars 3-D",
    "✋Predator 2",
    "Predator 2",
    "Pro Wrestling",
    "✋Pro Yakyuu GG League",
    "✋Pro Yakyuu GG League '94",
    "✋Putt & Putter",
    "Putt & Putter",
    "Rambo III",
    "Renegade",
    "Rescue Mission",
    "✋Riddick Bowe Boxing",
    "✋Rise of the Robots",
    "✋RoboCop 3",
    "RoboCop 3",
    "Rocky",
    "Running Battle",
    "Satellite 7",
    "Scramble Spirits",
    "✋Scratch Golf",
    "✋SD Gundam: Winner's History",
    "Sega Chess",
    "✋Sega Game Pack 4 in 1",
    "Sega World Tournament Golf",
    "Shadow Dancer",
    "Shadow of the Beast",
    "✋Shanghai II",
    "✋Shaq Fu",
    "✋Shikinjou",
    "Shooting Gallery",
    "✋Side Pocket",
    "Sítio do Picapau Amarelo",
    "✋Smash TV",
    "Smash TV",
    "✋Solitaire FunPak",
    "✋Solitaire Poker",
    "✋Sonic 2 in 1",
    "✋Sonic Blast",
    "Sonic Blast",
    "Space Gun",
    "✋Space Harrier",
    "Space Harrier",
    "Space Harrier 3-D",
    "Special Criminal Investigation",
    "✋Spider-Man vs. The Kingpin",
    "Spider-Man vs. The Kingpin",
    "✋Spider-Man: Return of the Sinister Six",
    "Spider-Man: Return of the Sinister Six",
    "✋Spider-Man/X-Men: Arcade's Revenge",
    "✋Sports Illustrated: Championship Football & Baseball",
    "✋Sports Trivia",
    "✋Sports Trivia: Championship Edition",
    "Spy vs. Spy",
    "✋Star Trek Generations: Beyond the Nexus",
    "✋Star Trek: The Next Generation – The Advanced Holodeck Tutorial",
    "✋Stargate",
    "Street Fighter II′: Champion Edition",
    "Strider",
    "Strider II",
    "Sukeban Deka II",
    "Summer Games",
    "✋Super Battletank",
    "✋Super Momotarou Dentetsu III",
    "✋Super Monaco GP",
    "Super Monaco GP",
    "Super Racing",
    "Super Tennis",
    "✋Superman: The Man of Steel",
    "Superman: The Man of Steel",
    "✋Surf Ninjas",
    "✋T2: The Arcade Game",
    "T2: The Arcade Game",
    "✋Taisen Mahjong HaoPai",
    "✋Taisen Mahjong HaoPai 2",
    "✋Taito Chase H.Q.",
    "Taito Chase H.Q.",
    "✋TaleSpin",
    "✋Tama & Friends: 3rd Street Park Tamalympics",
    "✋Tarzan: Lord of the Jungle",
    "✋Tatakae! Pro Yakyuu Twin League",
    "✋Taz in Escape from Mars",
    "Taz in Escape from Mars",
    "✋Taz-Mania: The Search for the Lost Seabirds",
    "Tecmo World Cup '93",
    "Tensai Bakabon",
    "✋Terminator 2: Judgment Day",
    "Terminator 2: Judgment Day",
    "✋The Addams Family",
    "The Addams Family",
    "✋The Adventures of Batman & Robin",
    "The Cyber Shinobi",
    "The Flintstones",
    "✋The Incredible Crash Dummies",
    "The Incredible Crash Dummies",
    "✋The Incredible Hulk",
    "The Incredible Hulk",
    "✋The Itchy & Scratchy Game",
    "✋The Ottifants",
    "The Ottifants",
    "✋The Pro Yakyuu '91",
    "✋The Quiz Gear Fight!!",
    "✋The Simpsons: Bart vs. the Space Mutants",
    "The Simpsons: Bart vs. the Space Mutants",
    "✋The Simpsons: Bart vs. the World",
    "The Simpsons: Bart vs. the World",
    "✋The Simpsons: Bartman Meets Radioactive Man",
    "Thunder Blade",
    "✋Tom & Jerry: The Movie",
    "Tom & Jerry: The Movie",
    "✋Torareta Tamaruka",
    "TransBot",
    "Trivial Pursuit: Genus Edition",
    "✋True Lies",
    "✋Ultimate Soccer",
    "Ultimate Soccer",
    "✋Virtua Fighter Animation",
    "Virtua Fighter Animation",
    "✋VR Troopers",
    "Wanted!",
    "✋Wheel of Fortune",
    "Where in the World is Carmen Sandiego?",
    "✋Winter Olympics: Lillehammer '94",
    "Winter Olympics: Lillehammer 94",
    "✋Wolfchild",
    "Wolfchild",
    "✋Woody Pop",
    "Woody Pop",
    "World Cup Italia '90",
    "✋World Cup USA '94",
    "World Cup USA '94",
    "✋World Derby",
    "World Games",
    "World Soccer",
    "✋WWF Raw",
    "✋WWF WrestleMania: Steel Cage Challenge",
    "WWF WrestleMania: Steel Cage Challenge",
    "X-Men 3: Mojo World",
    "✋X-Men: Gamesmaster's Legacy",
    "✋X-Men: Mojo World",
    "Xenon 2 Megablast",
    "✋Yu Yu Hakusho II: Gekitou! Nanakyou no Tatakai",
    "✋Yu Yu Hakusho: Horobishi Mono no Gyakushuu",
    "✋Zan Gear",
    "Zaxxon 3-D",
    ],
    F: [ // Terrible
    ],
    X: [ // Skip (SMS/GG has a lot of dupes; only keeping ideal version)
    "✋Alien 3",
    "✋Asterix and the Great Rescue",
    "✋Asterix and the Secret Mission",
    "✋Ayrton Senna's Super Monaco GP II",
    "Baku Baku Animal (Brazil)",
    "Batman Returns",
    "✋Bubble Bobble",
    "✋Castle of Illusion Starring Mickey Mouse",
    "✋Cheese Cat-Astrophe Starring Speedy Gonzales",
    "✋Chuck Rock",
    "✋Chuck Rock II: Son of Chuck",
    "Columns",
    "✋Cool Spot",
    "✋Daffy Duck in Hollywood",
    "✋Deep Duck Trouble Starring Donald Duck",
    "✋Desert Speedtrap Starring Road Runner & Wile E. Coyote",
    "Disney's Aladdin",
    "✋Disney's The Jungle Book",
    "Dr. Robotnik's Mean Bean Machine",
    "✋Dragon Crystal",
    "✋Ecco the Dolphin",
    "✋Ecco: The Tides of Time",
    "✋F1",
    "✋Fantastic Dizzy",
    "FIFA International Soccer",
    "✋Global Gladiators",
    "✋James Pond II: Codename: Robocod",
    "✋Joe Montana Football",
    "Jurassic Park",
    "Krusty's Fun House",
    "✋Land of Illusion Starring Mickey Mouse",
    "Legend of Illusion Starring Mickey Mouse (Brazil)",
    "✋Lemmings",
    "✋Micro Machines",
    "✋Olympic Gold: Barcelona '92",
    "✋Out Run Europa",
    "✋Paperboy",
    "✋Prince of Persia",
    "✋R.C. Grand Prix",
    "✋Rastan Saga",
    "✋Road Rash",
    "✋RoboCop Versus The Terminator",
    "✋Sensible Soccer",
    "Sonic Chaos",
    "Sonic Spinball",
    "✋Sonic the Hedgehog",
    "✋Sonic the Hedgehog 2",
    "✋Streets of Rage",
    "Streets of Rage 2",
    "✋Super Kick-Off",
    "Super Off Road",
    "✋Super Space Invaders",
    "✋The Lion King",
    "✋The Lucky Dime Caper Starring Donald Duck",
    "The Quest for the Shaven Yak Starring Ren Hoëk & Stimpy (Brazil)",
    "The Smurfs",
    "The Smurfs 2: Travel the World",
    "✋The Terminator",
    "✋Vampire: Master of Darkness",
    "✋Wimbledon",
    "✋Wonder Boy",
    "✋Wonder Boy: The Dragon's Trap",
    "✋World Class Leader Board Golf",
    "✋Zool: Ninja of the \"Nth\" Dimension",
    ],
};
